knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_OAUTH_ID)%'
            client_secret: '%env(GOOGLE_OAUTH_SECRET)%'
            redirect_route: auth_oauth_check
            redirect_params:
                service: google
